### ISSUE TITLE
Not working with Sony Bravia KDL-32EX525

### ISSUE THREAD

**Issue by gabriellluz** [cherezov/dlnap#14]
Hi there. I can't detect my Sony Bravia KDL-32EX525. It only detects my own pc as a device as 127.0.0.1. No external IPs?

I'm using Python 3.6 and no proxy.

Thanks a lot for this app. I've been looking for it for a long time since it creates new possibilities. I use eventghost for automation and a voice command like "Cast Iron Man" would play  that movie on my TV.

**Comment by SpootDev** [comment]
Are both devices on the same network subnet?

**Comment by gabriellluz** [comment]
Yes.

**Comment by gabriellluz** [comment]
It's working now.
