### ISSUE TITLE
_xml2dict() returns wrong result

### ISSUE THREAD

**Issue by 0x5e** [cherezov/dlnap#6]
`<sec:deviceID/>` in `root/device` was parsed as  the start of the node, not the node, which made his brother nodes behind him parsed as his childs.

**Comment by XenosLu** [comment]
I've found similar problems in this function and _xpath().
It seems that the author stopped paying attention in this project.
This forked version is still being updated: [ttopholm/dlnap](https://github.com/ttopholm/dlnap)

**Comment by XenosLu** [comment]
Thanks to danito, who fixed this issue days ago.
You can find the fixed version in  [ttopholm/dlnap](https://github.com/ttopholm/dlnap)
By the mean time, I am working on use lxml to parse all the xml data to avoid this kind of problem for good.

**Comment by cherezov** [comment]
@XenosLu  @ttopholm Thank you guys for keeping it alive.
Unfortunately I have no either time or environment to fix your issues and test them. I wish I'll merge your pull requests as soon as it will be possible and come back to support as well.
Thanks again!
